### ISSUE TITLE
Greykite and inconsistent timeseries?

### ISSUE THREAD

**Issue by Travis-Barton** [linkedin/greykite#6]
If my data is not sequential (has plenty of gaps), can Greykite handle it? I suspect that is the problem I am having with my data but I am not totally sure. 

EDIT: I see in Examine Input Data that greykite has an internal imputation method so let me be more clear. There is no specific time-frequency. I am not sampling data at a regular time interval. Data comes when it comes and there is no clear demarcation of the time interval. Would greykite be able to handle seemly randomly spaced and inconsistent input dates?

**Comment by Reza1317** [comment]
Hi Travis,

It might be best if you try to map your data to some time frequency (for example round your observed timestamps to hourly) and impute that on your end before using greykite (greykite can impute them too but you may know more about the data/ use case too impute better). The reason is otherwise one needs to make some sever assumptions. For example are the missing time values are really zero or are they some missing values close to the observed values? That would depend on the use case.

Reza
